[battery]
full_symbol = " 🔋"
charging_symbol = " 🔌"
discharging_symbol = " ⚡"

[[battery.display]]
threshold = 100
style = "bold red"

[character]
error_symbol = " [✖](bold red) "
success_symbol = " [➤](bold red)"

[directory]
truncation_length = 5
style = "bold italic white"
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
format = "[on](bold red) [$symbol$branch]($style) "
symbol = ' '
style = "bold yellow"

[git_commit]
commit_hash_length = 8
style = "bold white"


[hostname]
ssh_only = false
format = "[$hostname]($style) "
trim_at = "-"
style = "bold dimmed green"
disabled =false 

[python]
format = 'via [${symbol}${pyenv_prefix}(${version} )]($style)[(\($virtualenv\) )](bold red)'
style = "bold green"

[rust]
format = "[$symbol$version]($style) "
style = "bold green"

[username]
format = " [$user]($style)@"
style_user = "bold dimmed blue"
show_always = true

